-- db/06-aa-constraints-es.sql — renombra constraints/índices/FK físicos de aa a español
-- (Prisma RENAME puro; tablas/columnas ya estaban en español por db/05). Transaccional.
BEGIN;
SET search_path TO aa;
ALTER TABLE "agente" RENAME CONSTRAINT "Agent_pkey" TO "agente_pkey";
ALTER TABLE "agente_skill" RENAME CONSTRAINT "AgentSkill_pkey" TO "agente_skill_pkey";
ALTER TABLE "automatizacion" RENAME CONSTRAINT "Automation_pkey" TO "automatizacion_pkey";
ALTER TABLE "cita" RENAME CONSTRAINT "Appointment_pkey" TO "cita_pkey";
ALTER TABLE "conexion_canal" RENAME CONSTRAINT "ChannelConnection_pkey" TO "conexion_canal_pkey";
ALTER TABLE "configuracion_sistema" RENAME CONSTRAINT "SystemConfig_pkey" TO "configuracion_sistema_pkey";
ALTER TABLE "contacto_prospecto" RENAME CONSTRAINT "ProspectContact_pkey" TO "contacto_prospecto_pkey";
ALTER TABLE "conversacion" RENAME CONSTRAINT "Conversation_pkey" TO "conversacion_pkey";
ALTER TABLE "ejecucion_automatizacion" RENAME CONSTRAINT "AutomationRun_pkey" TO "ejecucion_automatizacion_pkey";
ALTER TABLE "estudio_mercado" RENAME CONSTRAINT "MarketStudy_pkey" TO "estudio_mercado_pkey";
ALTER TABLE "fragmento_conocimiento" RENAME CONSTRAINT "KnowledgeChunk_pkey" TO "fragmento_conocimiento_pkey";
ALTER TABLE "franja_horaria" RENAME CONSTRAINT "TimeSlot_pkey" TO "franja_horaria_pkey";
ALTER TABLE "horario_agente" RENAME CONSTRAINT "AgentSchedule_pkey" TO "horario_agente_pkey";
ALTER TABLE "integracion" RENAME CONSTRAINT "Integration_pkey" TO "integracion_pkey";
ALTER TABLE "landing_lead" RENAME CONSTRAINT "LandingLead_pkey" TO "landing_lead_pkey";
ALTER TABLE "landing_project" RENAME CONSTRAINT "LandingProject_pkey" TO "landing_project_pkey";
ALTER TABLE "lead" RENAME CONSTRAINT "Lead_pkey" TO "lead_pkey";
ALTER TABLE "linea_presupuesto" RENAME CONSTRAINT "BudgetLine_pkey" TO "linea_presupuesto_pkey";
ALTER TABLE "mensaje" RENAME CONSTRAINT "Message_pkey" TO "mensaje_pkey";
ALTER TABLE "presupuesto" RENAME CONSTRAINT "Budget_pkey" TO "presupuesto_pkey";
ALTER TABLE "rango_bloqueo" RENAME CONSTRAINT "BlockedRange_pkey" TO "rango_bloqueo_pkey";
ALTER TABLE "servicio_agente" RENAME CONSTRAINT "Service_pkey" TO "servicio_agente_pkey";
ALTER TABLE "skill" RENAME CONSTRAINT "Skill_pkey" TO "skill_pkey";
ALTER TABLE "tenant" RENAME CONSTRAINT "Client_pkey" TO "tenant_pkey";
ALTER TABLE "uso_tokens" RENAME CONSTRAINT "TokenUsage_pkey" TO "uso_tokens_pkey";
ALTER TABLE "usuario" RENAME CONSTRAINT "User_pkey" TO "usuario_pkey";
ALTER TABLE "agente_skill" RENAME CONSTRAINT "AgentSkill_agentId_fkey" TO "agente_skill_agente_id_fkey";
ALTER TABLE "agente_skill" RENAME CONSTRAINT "AgentSkill_skillId_fkey" TO "agente_skill_skill_id_fkey";
ALTER TABLE "automatizacion" RENAME CONSTRAINT "Automation_agentId_fkey" TO "automatizacion_agente_id_fkey";
ALTER TABLE "cita" RENAME CONSTRAINT "Appointment_leadId_fkey" TO "cita_lead_id_fkey";
ALTER TABLE "cita" RENAME CONSTRAINT "Appointment_serviceId_fkey" TO "cita_servicio_id_fkey";
ALTER TABLE "cita" RENAME CONSTRAINT "Appointment_slotId_fkey" TO "cita_franja_id_fkey";
ALTER TABLE "conexion_canal" RENAME CONSTRAINT "ChannelConnection_agentId_fkey" TO "conexion_canal_agente_id_fkey";
ALTER TABLE "conversacion" RENAME CONSTRAINT "Conversation_agentId_fkey" TO "conversacion_agente_id_fkey";
ALTER TABLE "ejecucion_automatizacion" RENAME CONSTRAINT "AutomationRun_automationId_fkey" TO "ejecucion_automatizacion_automatizacion_id_fkey";
ALTER TABLE "fragmento_conocimiento" RENAME CONSTRAINT "KnowledgeChunk_agentId_fkey" TO "fragmento_conocimiento_agente_id_fkey";
ALTER TABLE "franja_horaria" RENAME CONSTRAINT "TimeSlot_serviceId_fkey" TO "franja_horaria_servicio_id_fkey";
ALTER TABLE "horario_agente" RENAME CONSTRAINT "AgentSchedule_agentId_fkey" TO "horario_agente_agente_id_fkey";
ALTER TABLE "integracion" RENAME CONSTRAINT "Integration_agentId_fkey" TO "integracion_agente_id_fkey";
ALTER TABLE "lead" RENAME CONSTRAINT "Lead_agentId_fkey" TO "lead_agente_id_fkey";
ALTER TABLE "lead" RENAME CONSTRAINT "Lead_conversationId_fkey" TO "lead_conversacion_id_fkey";
ALTER TABLE "linea_presupuesto" RENAME CONSTRAINT "BudgetLine_budgetId_fkey" TO "linea_presupuesto_presupuesto_id_fkey";
ALTER TABLE "mensaje" RENAME CONSTRAINT "Message_conversationId_fkey" TO "mensaje_conversacion_id_fkey";
ALTER TABLE "rango_bloqueo" RENAME CONSTRAINT "BlockedRange_scheduleId_fkey" TO "rango_bloqueo_horario_id_fkey";
ALTER TABLE "servicio_agente" RENAME CONSTRAINT "Service_agentId_fkey" TO "servicio_agente_agente_id_fkey";
ALTER INDEX "Agent_publicKey_key" RENAME TO "agente_clave_publica_key";
ALTER INDEX "Appointment_createdAt_idx" RENAME TO "cita_creado_en_idx";
ALTER INDEX "Appointment_leadId_idx" RENAME TO "cita_lead_id_idx";
ALTER INDEX "Appointment_slotId_idx" RENAME TO "cita_franja_id_idx";
ALTER INDEX "Appointment_slotId_key" RENAME TO "cita_franja_id_key";
ALTER INDEX "ChannelConnection_agentId_provider_key" RENAME TO "conexion_canal_agente_id_proveedor_key";
ALTER INDEX "ProspectContact_codigo_key" RENAME TO "contacto_prospecto_codigo_key";
ALTER INDEX "ProspectContact_createdAt_idx" RENAME TO "contacto_prospecto_creado_en_idx";
ALTER INDEX "ProspectContact_deletedAt_idx" RENAME TO "contacto_prospecto_eliminado_en_idx";
ALTER INDEX "ProspectContact_type_contactado_idx" RENAME TO "contacto_prospecto_tipo_contactado_idx";
ALTER INDEX "AutomationRun_automationId_createdAt_idx" RENAME TO "ejecucion_automatizacion_automatizacion_id_creado_en_idx";
ALTER INDEX "MarketStudy_createdAt_idx" RENAME TO "estudio_mercado_creado_en_idx";
ALTER INDEX "KnowledgeChunk_agentId_idx" RENAME TO "fragmento_conocimiento_agente_id_idx";
ALTER INDEX "TimeSlot_serviceId_available_idx" RENAME TO "franja_horaria_servicio_id_disponible_idx";
ALTER INDEX "TimeSlot_serviceId_startTime_key" RENAME TO "franja_horaria_servicio_id_inicio_key";
ALTER INDEX "TimeSlot_startTime_idx" RENAME TO "franja_horaria_inicio_idx";
ALTER INDEX "AgentSchedule_agentId_key" RENAME TO "horario_agente_agente_id_key";
ALTER INDEX "Integration_agentId_provider_key" RENAME TO "integracion_agente_id_proveedor_key";
ALTER INDEX "LandingLead_createdAt_idx" RENAME TO "landing_lead_creado_en_idx";
ALTER INDEX "LandingProject_updatedAt_idx" RENAME TO "landing_project_actualizado_en_idx";
ALTER INDEX "Lead_agentId_createdAt_idx" RENAME TO "lead_agente_id_creado_en_idx";
ALTER INDEX "Lead_conversationId_key" RENAME TO "lead_conversacion_id_key";
ALTER INDEX "BudgetLine_budgetId_idx" RENAME TO "linea_presupuesto_presupuesto_id_idx";
ALTER INDEX "Message_conversationId_createdAt_idx" RENAME TO "mensaje_conversacion_id_creado_en_idx";
ALTER INDEX "Budget_clientId_createdAt_idx" RENAME TO "presupuesto_tenant_id_creado_en_idx";
ALTER INDEX "Budget_quoteNumber_key" RENAME TO "presupuesto_numero_presupuesto_key";
ALTER INDEX "BlockedRange_scheduleId_startDate_idx" RENAME TO "rango_bloqueo_horario_id_fecha_inicio_idx";
ALTER INDEX "Service_agentId_idx" RENAME TO "servicio_agente_agente_id_idx";
ALTER INDEX "Service_agentId_name_key" RENAME TO "servicio_agente_agente_id_nombre_key";
ALTER INDEX "Skill_name_key" RENAME TO "skill_nombre_key";
ALTER INDEX "Client_codCliente_key" RENAME TO "tenant_codigo_key";
ALTER INDEX "TokenUsage_clientId_createdAt_idx" RENAME TO "uso_tokens_tenant_id_creado_en_idx";
ALTER INDEX "User_email_key" RENAME TO "usuario_email_key";
COMMIT;
